#!/usr/bin/env bash
#
# DOTBOT install script
# Updates dotbot, sets config and plugins
#
# Camron Flanders <me@camronflanders.com>

set -e

CONFIG="install.conf.yaml"
DOTBOT_LIB_DIR="./lib"
DOTBOT_DIR="${DOTBOT_LIB_DIR}/dotbot"
DOTBOT_PLUGIN_GLOB="${DOTBOT_LIB_DIR}/dotbot-*"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTBOT_CMD="${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# automatically find/add dotbot plugins to script
PLUGIN_DIR_OPTS=
for plug in $DOTBOT_PLUGIN_GLOB; do
    PLUGIN_DIR_OPTS="$PLUGIN_DIR_OPTS --plugin-dir $plug"
done

$DOTBOT_CMD \
    -c "${CONFIG}" \
    -d "${BASEDIR}" \
    ${PLUGIN_DIR_OPTS} \
    "${@}"
