require('plugin.git-conflict')
require('plugin.hop')
require('plugin.lsp-lines')
require('plugin.mason')
require('plugin.mason-lspconfig')
require('plugin.nvim-cmp')
require('plugin.nvim-lspconfig')
require('plugin.nvim-telescope')
require('plugin.nvim-treesitter')
require('plugin.template-string')
require('plugin.todo-comments')
require('plugin.trouble')

require('theme.catppuccin')
