require('plugin.hop')
require('plugin.lsp-lines')
require('plugin.nvim-compe')
require('plugin.nvim-lspconfig')
require('plugin.nvim-telescope')
require('plugin.nvim-treesitter')
require('plugin.trouble')
