---
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-camron}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-camron}
      POSTGRES_DB: ${POSTGRES_DATABASE:-camron}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:7
    ports:
      - ${VALKEY_PORT:-6379}:6379
    volumes:
      - valkey_data:/bitnami/valkey/data

volumes:
  postgres_data:
    driver: local
  valkey_data:
    driver: local

networks:
  default:
