add_newline = false

format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_state\
  $git_status\
  $nix_shell\
  $cmd_duration\
  $line_break\
  $jobs\
  $time\
  $character\
  """

right_format = """\
  $battery\
"""

[battery]
format = '[$percentage $symbol]($style)'
[[battery.display]]
threshold = 20

[character]
success_symbol = ">:"
error_symbol = ">:"

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
