"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_state\
  $git_status\
  $nix_shell\
  $cmd_duration\
  $line_break\
  $jobs\
  $time\
  $character\
  """

right_format = """\
  $direnv\
  $battery\
"""

[battery]
format = '[$percentage $symbol]($style)'
[[battery.display]]
threshold = 20

[character]
success_symbol = ">:"
error_symbol = ">:"

[direnv]
disabled = false
detect_files = ['.envrc', '.env', '.env.local']
# "loaded" doesn't seem to actually mean the ENV is loaded, just that there is
# relevant files present. For now, we'll just remove $loaded from the format
format = '[($symbol$allowed)]($style) '
style = 'italic white'
allowed_msg = '✅'
not_allowed_msg = '⭕️'
denied_msg = '⭕️'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
