# ENV
# loaded from .zshenv

# asdf | mise | vfox
environment_manager=mise
# direnv | mise
local_env_manager=mise
# atuin | mcfly
history_manager=atuin
# "fnox" | "none"
secrets_manager=fnox

# prefixing these files with dot because of my dotbot config, maybe change this later
source "$ZDOTDIR/.aliases.zsh"
source "$ZDOTDIR/.options.zsh"

# setup wezterm shell integration: https://wezfurlong.org/wezterm/shell-integration.html
. "$CBFDOTFILES_DIR/config/wezterm/shell-integration.sh"

export PATH="$CBFDOTFILES_DIR/config/zsh/zfunctions:$CBFDOTFILES_DIR/bin:$PATH"

# homebrew
BREW_DIR=/opt/homebrew
BREW_CMD="$BREW_DIR/bin/brew"
eval "$($BREW_DIR/bin/brew shellenv)"

export CFLAGS="-I$BREW_DIR/include"
export LDFLAGS="-L$BREW_DIR/lib"

# append completions to fpath
fpath=(${ZDOTDIR}/completions $fpath)

if [ "$environment_manager" = "asdf" ]; then
    # ASDF-VM
    # https://asdf-vm.com/#/core-manage-asdf
    . $HOME/.asdf/asdf.sh

    fpath=(${ASDF_DIR}/completions $fpath)

    # rust
    . "$(asdf where rust)/env"
elif [ "$environment_manager" = "vfox" ]; then
    # Try vfox as replacement for ASDF, comment ASDF above
    # VFOX https://vfox.lhan.me/guides/quick-start.html
    eval "$(vfox activate zsh)"
elif [ "$environment_manager" = "mise" ]; then
    eval "$(mise activate zsh)"
fi

if [ "$secrets_manager" = "fnox" ]; then
    # https://fnox.jdx.dev
    eval "$(fnox activate zsh)"
fi

# FASD
# Quick jump to directories/etc
# aliased to z and zz
if hash fasd; then
    eval "$(fasd --init auto)"
fi

# prompt
if hash starship; then
    eval "$(starship init zsh)"
else
    echo "no starship?"
fi

# cache the compdump once per day
# TODO: fix autocompletes
autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C


# Source autocompletions for ZSH
# for cf in $CBFDOTFILES_DIR/config/zsh/completions/*.zsh_completion;
#     do source $cf;
# done

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
 source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
else
 echo "[ERROR] zprezto not installed!"
fi

# To profile zsh bootup
# zmodload zsh/zprof # top of your .zshrc file
# zprof # keep at the end

# Added by Docker Desktop
if [[ -s "${ZDOTDIR:-$HOME}/.docker/init-zsh.sh" ]]; then
    source $HOME/.docker/init-zsh.sh || true
fi


if [[ "$history_manager" == "atuin" ]]; then
    # atuin (shell history)
    # https://atuin.sh/
    # https://github.com/ellie/atuin
    #
    # Don't let atuin auto-bind to up and ctrl-r
    # The current full UI "up" implementation is too bloated and incongruous
    export ATUIN_NOBIND="true"
    eval "$(atuin init zsh)"
    # ctrl+r for full atuin view
    bindkey '^r' _atuin_search_widget
fi

if [[ "$history_manager" == "mcfly" ]]; then
    eval "$(mcfly init zsh)"
fi

if [[ "$local_env_manager" == "direnv" ]]; then
    # direnv
    eval "$(direnv hook zsh)"
fi

# interactive directory walking (https://github.com/antonmedv/walk)
function w {
  cd "$(walk "$@")"
}

# UV (https://docs.astral.sh/uv/getting-started/installation/#upgrading-uv)
# add autocompletions
if hash uv &> /dev/null; then
    eval "$(uv --generate-shell-completion zsh)"
fi

if hash uvx &> /dev/null; then
    eval "$(uvx --generate-shell-completion zsh)"
fi

if [ -f "$ZDOTDIR/.zshenv.private" ] && hash op &> /dev/null; then
    eval $(op inject -i $ZDOTDIR/.zshenv.private)
fi

## LULA LIFE PHPBREW
export PHPBREW_RC_ENABLE=1
source /Users/camron/.phpbrew/bashrc
_phpbrewrc_load # force eval of phpbrew after loading
