#!/usr/bin/env bash
#MISE description="Run neovim nightly with nvim-12 configuration"

export NVIM_APPNAME=nvim-12

# use the cwd where we called the script, not where the script is configured
cd "$MISE_ORIGINAL_CWD"
mise exec neovim@nightly -- nvim
